# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssh_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rssh_log.proto\x12\x0cssh_analysis\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n\x0cIPLookupData\x12\x0b\n\x03lat\x18\x07 \x01(\x02\x12\x0b\n\x03lon\x18\x08 \x01(\x02\x12\x11\n\tcontinent\x18\t \x01(\t\x12\x18\n\x10\x63ountry_iso_code\x18\n \x01(\t\x12\x14\n\x0c\x63ountry_name\x18\x0b \x01(\t\x12\x14\n\x0csubdivisions\x18\x0c \x03(\t\x12\x10\n\x08timezone\x18\r \x01(\t\x12\x13\n\x0bpostal_code\x18\x0e \x01(\t\x12\x0c\n\x04\x63ity\x18\x0f \x01(\t\"\xcc\x01\n\x06SSHLog\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11validLoginAttempt\x18\x02 \x01(\x08\x12\x17\n\x0fusernameIsValid\x18\x03 \x01(\x08\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\x11\n\tipAddress\x18\x05 \x01(\t\x12\x0c\n\x04port\x18\x06 \x01(\x05\x12\x30\n\x0cipLookupData\x18\x07 \x01(\x0b\x32\x1a.ssh_analysis.IPLookupData\"-\n\x07SSHLogs\x12\"\n\x04logs\x18\x01 \x03(\x0b\x32\x14.ssh_analysis.SSHLogb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssh_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IPLOOKUPDATA._serialized_start=65
  _IPLOOKUPDATA._serialized_end=247
  _SSHLOG._serialized_start=250
  _SSHLOG._serialized_end=454
  _SSHLOGS._serialized_start=456
  _SSHLOGS._serialized_end=501
# @@protoc_insertion_point(module_scope)
